x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 20m
      max-file: "3"

services:
  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile.binary
    image: cosmos-validator-watcher:local
    pull_policy: never
    user: cosmos-monitoring
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - monitoring-data:/data
    entrypoint:
      - cosmos-validator-watcher
      - --http-addr
      - ":${MONITORING_PORT}"
      - --node
      - ${MONITORING_RPC_ENDPOINT}
      - --validator
      - ${MONITORING_VALIDATOR}
    labels:
        - traefik.enable=false
        - metrics.scrape=true
        - metrics.path=/metrics
        - metrics.port=${MONITORING_PORT}
        - metrics.instance=monitoring
        - metrics.network=${NETWORK}

volumes:
  monitoring-data:
